export interface AllergenDefinition {
  id: string;
  icon: string;
  names: Record<string, string>;
  details: Record<string, string>;
}

export const ALLERGEN_CATALOG: AllergenDefinition[] = [
  {
    id: 'GLUTEN',
    icon: '🌾',
    names: {
      tr: 'Gluten',
      en: 'Gluten',
      de: 'Gluten',
      es: 'Gluten',
      fr: 'Gluten',
      ja: 'グルテン',
      zh: '麸质 / 谷蛋白',
      ru: 'Глютен',
      ar: 'الغلوتين',
      pt: 'Glúten',
      id: 'Gluten',
    },
    details: {
      tr: 'Buğday, çavdar, arpa, yulaf vb. tahıllar',
      en: 'Wheat, rye, barley, oats, and spelt',
      de: 'Weizen, Roggen, Gerste, Hafer',
      es: 'Trigo, centeno, cebada, avena',
      fr: 'Blé, seigle, orge, avoine',
      ja: '小麦、ライ麦、大麦、オート麦などの穀物',
      zh: '小麦、黑麦、大麦、燕麦等谷物',
      ru: 'Пшеница, рожь, ячмень, овес и их производные',
      ar: 'القمح، الجاودار، الشعير، الشوفان ومشتقاتها',
      pt: 'Trigo, centeio, cevada, aveia e espelta',
      id: 'Gandum, rye, barley, oat, dan serealia sejenis',
    },
  },
  {
    id: 'DAIRY',
    icon: '🥛',
    names: {
      tr: 'Süt / Laktoz',
      en: 'Milk & Dairy',
      de: 'Milch / Laktose',
      es: 'Leche / Lácteos',
      fr: 'Lait / Lactose',
      ja: '乳製品 / ラクトース',
      zh: '乳制品 / 乳糖',
      ru: 'Молоко / Лактоза',
      ar: 'الحليب واللاكتوز',
      pt: 'Leite / Lactose',
      id: 'Susu / Laktosa',
    },
    details: {
      tr: 'Süt, tereyağı, peynir, krema, yoğurt',
      en: 'Milk, butter, cheese, cream, yogurt',
      de: 'Milch, Butter, Käse, Sahne, Joghurt',
      es: 'Leche, mantequilla, queso, crema, yogur',
      fr: 'Lait, beurre, fromage, crème, yaourt',
      ja: '牛乳、バター、チーズ、クリーム、ヨーグルト',
      zh: '牛奶、黄油、奶酪、奶油、酸奶',
      ru: 'Молоко, сливочное масло, сыр, сливки, йогурт',
      ar: 'الحليب، الزبدة، الجبن، الكريمة، والزبادي',
      pt: 'Leite, manteiga, queijo, natas, iogurte',
      id: 'Susu, mentega, keju, krim, yogurt',
    },
  },
  {
    id: 'EGGS',
    icon: '🥚',
    names: {
      tr: 'Yumurta',
      en: 'Eggs',
      de: 'Eier',
      es: 'Huevos',
      fr: 'Œufs',
      ja: '卵',
      zh: '鸡蛋',
      ru: 'Яйца',
      ar: 'البيض',
      pt: 'Ovos',
      id: 'Telur',
    },
    details: {
      tr: 'Tüm yumurta ve yumurta içeren ürünler',
      en: 'Eggs and egg-derived ingredients',
      de: 'Eier und daraus hergestellte Erzeugnisse',
      es: 'Huevos y productos a base de huevo',
      fr: 'Œufs et produits à base d’œufs',
      ja: 'すべての卵および卵由来の製品',
      zh: '所有蛋类及含蛋配料食品',
      ru: 'Яйца и продукты на их основе',
      ar: 'البيض وجميع المكونات المشتقة من البيض',
      pt: 'Ovos e produtos à base de ovos',
      id: 'Telur dan semua produk olahan telur',
    },
  },
  {
    id: 'PEANUTS',
    icon: '🥜',
    names: {
      tr: 'Yer Fıstığı',
      en: 'Peanuts',
      de: 'Erdnüsse',
      es: 'Cacahuetes',
      fr: 'Arachides',
      ja: '落花生 (ピーナッツ)',
      zh: '花生',
      ru: 'Арахис',
      ar: 'الفول السوداني',
      pt: 'Amendoins',
      id: 'Kacang Tanah',
    },
    details: {
      tr: 'Yer fıstığı ve fıstık yağı/ezmesi',
      en: 'Peanuts and peanut oil/butter',
      de: 'Erdnüsse und Erdnussöl',
      es: 'Cacahuetes y aceite de cacahuete',
      fr: 'Arachides et dérivés',
      ja: '落花生、ピーナッツオイル、ピーナッツバター',
      zh: '花生及花生油、花生酱',
      ru: 'Арахис, арахисовое масло и паста',
      ar: 'الفول السوداني وزيت الفول السوداني وزبدته',
      pt: 'Amendoim, manteiga e óleo de amendoim',
      id: 'Kacang tanah, minyak kacang, dan selai kacang',
    },
  },
  {
    id: 'TREE_NUTS',
    icon: '🌰',
    names: {
      tr: 'Sert Kabuklu Yemişler',
      en: 'Tree Nuts',
      de: 'Schalenfrüchte',
      es: 'Frutos de Cáscara',
      fr: 'Fruits à Coque',
      ja: '木の実類 (ナッツ類)',
      zh: '坚果',
      ru: 'Орехи',
      ar: 'المكسرات الشجرية',
      pt: 'Frutos de Casca Rija',
      id: 'Kacang Pohon',
    },
    details: {
      tr: 'Badem, fındık, ceviz, kaju, antep fıstığı',
      en: 'Almonds, hazelnuts, walnuts, cashews, pistachios',
      de: 'Mandeln, Haselnüsse, Walnüsse, Cashews',
      es: 'Almendras, avellanas, nueces, anacardos',
      fr: 'Amandes, noisettes, noix, pistaches',
      ja: 'アーモンド、ヘーゼルナッツ、クルミ、カシューナッツ、ピスタチオ',
      zh: '杏仁、榛子、核桃、腰果、开心果',
      ru: 'Миндаль, фундук, грецкий орех, кешью, фисташки',
      ar: 'اللوز، البندق، الجوز، الكاجو، والفستق',
      pt: 'Amêndoas, avelãs, nozes, cajus, pistácios',
      id: 'Almond, hazelnut, kenari, kacang mede, pistachio',
    },
  },
  {
    id: 'SOY',
    icon: '🌱',
    names: {
      tr: 'Soya',
      en: 'Soybeans',
      de: 'Soja',
      es: 'Soja',
      fr: 'Soja',
      ja: '大豆',
      zh: '大豆',
      ru: 'Соя',
      ar: 'الصويا',
      pt: 'Soja',
      id: 'Kedelai',
    },
    details: {
      tr: 'Soya fasulyesi, soya sosu, tofu, lesitin',
      en: 'Soybeans, soy sauce, tofu, soy lecithin',
      de: 'Sojabohnen, Sojasauce, Tofu',
      es: 'Soja, salsa de soja, tofu',
      fr: 'Soja, sauce soja, tofu',
      ja: '大豆、醤油、豆腐、大豆レシチン',
      zh: '大豆、酱油、豆腐、大豆卵磷脂',
      ru: 'Соевые бобы, соевый соус, тофу, лецитин',
      ar: 'فول الصويا، صلصة الصويا، التوفو، والليسيثين',
      pt: 'Grãos de soja, molho de soja, tofu, lecitina',
      id: 'Kedelai, kecap, tahu, lesitin kedelai',
    },
  },
  {
    id: 'FISH',
    icon: '🐟',
    names: {
      tr: 'Balık',
      en: 'Fish',
      de: 'Fisch',
      es: 'Pescado',
      fr: 'Poisson',
      ja: '魚類',
      zh: '鱼类',
      ru: 'Рыба',
      ar: 'الأسماك',
      pt: 'Peixe',
      id: 'Ikan',
    },
    details: {
      tr: 'Tüm balık türleri ve balık sosları',
      en: 'All fish species and fish-derived sauces',
      de: 'Alle Fischarten und Fischerzeugnisse',
      es: 'Todo tipo de pescados y salsas de pescado',
      fr: 'Tous poissons et dérivés',
      ja: 'すべての魚種および魚醤製品',
      zh: '所有鱼类及鱼露、鱼类调味品',
      ru: 'Все виды рыбы и рыбные соусы',
      ar: 'جميع أنواع الأسماك وصلصات السمك',
      pt: 'Todas as espécies de peixes e molhos derivados',
      id: 'Semua jenis ikan dan saus berbahan dasar ikan',
    },
  },
  {
    id: 'CRUSTACEANS',
    icon: '🦐',
    names: {
      tr: 'Kabuklular',
      en: 'Crustaceans',
      de: 'Krebstiere',
      es: 'Crustáceos',
      fr: 'Crustacés',
      ja: '甲殻類',
      zh: '甲壳类水产',
      ru: 'Ракообразные',
      ar: 'القشريات',
      pt: 'Crustáceos',
      id: 'Krustasea (Udang & Kepiting)',
    },
    details: {
      tr: 'Karides, yengeç, ıstakoz, kerevit',
      en: 'Prawns, crabs, lobster, crayfish',
      de: 'Garnelen, Krabben, Hummer',
      es: 'Gambas, langostinos, cangrejos',
      fr: 'Crevettes, crabes, homards',
      ja: 'エビ、カニ、ロブスター、ザリガニ',
      zh: '虾、蟹、龙虾、小龙虾',
      ru: 'Креветки, крабы, омары, лангусты',
      ar: 'الروبيان، السلطعون، الكركند، وجراد البحر',
      pt: 'Camarão, caranguejo, lagosta, lagostim',
      id: 'Udang, kepiting, lobster, dan rajungan',
    },
  },
  {
    id: 'MOLLUSCS',
    icon: '🦪',
    names: {
      tr: 'Yumuşakçalar',
      en: 'Molluscs',
      de: 'Weichtiere',
      es: 'Moluscos',
      fr: 'Mollusques',
      ja: '軟体動物',
      zh: '软体动物',
      ru: 'Моллюски',
      ar: 'الرخويات',
      pt: 'Moluscos',
      id: 'Moluska (Kerang & Cumi)',
    },
    details: {
      tr: 'Midye, istiridye, ahtapot, kalamar, salyangoz',
      en: 'Mussels, oysters, squid, octopus, snails',
      de: 'Muscheln, Austern, Tintenfisch, Schnecken',
      es: 'Mejillones, ostras, calamares, pulpo',
      fr: 'Moules, huîtres, calmars, poulpe',
      ja: 'ムール貝、牡蠣、イカ、タコ、エスカルゴ',
      zh: '贻贝、生蚝、鱿鱼、章鱼、蜗牛',
      ru: 'Мидии, устрицы, кальмары, осьминоги, улитки',
      ar: 'بلح البحر، المحار، الحبار، الأخطبوط، والحلزون',
      pt: 'Mexilhões, ostras, lulas, polvo, caracóis',
      id: 'Kerang, tiram, cumi-cumi, gurita, bekicot',
    },
  },
  {
    id: 'SESAME',
    icon: '🥯',
    names: {
      tr: 'Susam',
      en: 'Sesame',
      de: 'Sesamsamen',
      es: 'Sésamo',
      fr: 'Sésame',
      ja: 'ごま',
      zh: '芝麻',
      ru: 'Кунжут',
      ar: 'السمسم',
      pt: 'Sésamo / Gergelim',
      id: 'Wijen',
    },
    details: {
      tr: 'Susam tohumu, tahin, susam yağı',
      en: 'Sesame seeds, tahini, sesame oil',
      de: 'Sesamsamen, Tahin, Sesamöl',
      es: 'Semillas de sésamo, tahini, aceite de sésamo',
      fr: 'Graines de sésame, tahini, huile de sésame',
      ja: 'ごま、タヒニ、ごま油',
      zh: '芝麻粒、芝麻酱、芝麻油',
      ru: 'Семена кунжута, тахини, кунжутное масло',
      ar: 'بذور السمسم، الطحينة، وزيت السمسم',
      pt: 'Sementes de sésamo, tahini, óleo de sésamo',
      id: 'Biji wijen, pasta tahini, dan minyak wijen',
    },
  },
  {
    id: 'MUSTARD',
    icon: '🌭',
    names: {
      tr: 'Hardal',
      en: 'Mustard',
      de: 'Senf',
      es: 'Mostaza',
      fr: 'Moutarde',
      ja: 'マスタード (からし)',
      zh: '芥末',
      ru: 'Горчица',
      ar: 'الخردل',
      pt: 'Mostarda',
      id: 'Mustard (Biji Sawi)',
    },
    details: {
      tr: 'Hardal tohumu, hardal tozu, soslar',
      en: 'Mustard seeds, powder, dressings',
      de: 'Senfkörner, Senfpulver, Saucen',
      es: 'Semillas de mostaza, salsas',
      fr: 'Graines de moutarde, condiments',
      ja: 'マスタードシード、からし粉、マスタードソース',
      zh: '芥末籽、芥末粉、调味芥末酱',
      ru: 'Семена горчицы, горчичный порошок, соусы',
      ar: 'بذور الخردل، مسحوق الخردل، والصلصات',
      pt: 'Sementes de mostarda, pó e molhos de mostarda',
      id: 'Biji mustard, bubuk mustard, dan saus mustard',
    },
  },
  {
    id: 'CELERY',
    icon: '🥬',
    names: {
      tr: 'Kereviz',
      en: 'Celery',
      de: 'Sellerie',
      es: 'Apio',
      fr: 'Céleri',
      ja: 'セロリ',
      zh: '芹菜',
      ru: 'Сельдерей',
      ar: 'الكرفس',
      pt: 'Aipo',
      id: 'Seledri',
    },
    details: {
      tr: 'Kereviz sapı, yaprağı, kökü ve tohumu',
      en: 'Celery stalks, leaves, roots, seeds',
      de: 'Staudensellerie, Knolle, Samen',
      es: 'Tallos, hojas, raíces de apio',
      fr: 'Branches, feuilles, graines de céleri',
      ja: 'セロリの茎、葉、根、種子',
      zh: '芹菜茎、叶、根及芹菜籽',
      ru: 'Стебли, листья, корни и семена сельдерея',
      ar: 'سيقان الكرفس، أوراقه، جذوره، وبذوره',
      pt: 'Talos, folhas, raízes e sementes de aipo',
      id: 'Batang, daun, akar, dan biji seledri',
    },
  },
  {
    id: 'LUPIN',
    icon: '🌸',
    names: {
      tr: 'Lupin (Acıbakla)',
      en: 'Lupin',
      de: 'Lupinen',
      es: 'Altramuces',
      fr: 'Lupin',
      ja: 'ルピナス (白花ハウチワマメ)',
      zh: '羽扇豆',
      ru: 'Люпин',
      ar: 'الترمس',
      pt: 'Tremoço',
      id: 'Lupin (Kacang Lupini)',
    },
    details: {
      tr: 'Lupin tohumu ve unu (unlu mamüllerde)',
      en: 'Lupin seeds and flour in baked goods',
      de: 'Lupinensamen und -mehl',
      es: 'Semillas y harina de altramuz',
      fr: 'Graines et farine de lupin',
      ja: 'ルピナス種子および製菓・製パン用粉',
      zh: '羽扇豆籽及烘焙食品中的羽扇豆粉',
      ru: 'Семена и мука люпина в выпечке',
      ar: 'بذور ودقيق الترمس في المخبوزات',
      pt: 'Sementes e farinha de tremoço em panificação',
      id: 'Biji dan tepung lupin pada produk roti',
    },
  },
  {
    id: 'SULPHITES',
    icon: '🍷',
    names: {
      tr: 'Kükürt Dioksit / Sülfitler',
      en: 'Sulphur Dioxide & Sulphites',
      de: 'Schwefeldioxid / Sulfite',
      es: 'Dióxido de Azufre / Sulfitos',
      fr: 'Anhydride Sulfureux / Sulfites',
      ja: '亜硫酸塩 / 二酸化硫黄',
      zh: '二氧化硫及亚硫酸盐',
      ru: 'Диоксид серы и сульфиты',
      ar: 'ثاني أكسيد الكبريت والكبريتيت',
      pt: 'Dióxido de Enxofre e Sulfitos',
      id: 'Sulfur Dioksida & Sulfit',
    },
    details: {
      tr: 'Kuru meyveler, şarap, sirke koruyucuları (>10mg/kg)',
      en: 'Dried fruits, wine, vinegar preservatives (>10mg/kg)',
      de: 'Trockenfrüchte, Wein, Konservierungsstoffe',
      es: 'Frutos secos, vino, conservantes',
      fr: 'Fruits secs, vin, conservateurs',
      ja: 'ドライフルーツ、ワイン、酢の保存料 (>10mg/kg)',
      zh: '干果、葡萄酒、醋类防腐剂（>10mg/kg）',
      ru: 'Сухофрукты, вино, уксус, консерванты (>10мг/кг)',
      ar: 'الفواكه المجففة، الخل، ومواد الحفظ (>10 ملغ/كغ)',
      pt: 'Frutos secos, vinho, conservantes em vinagres (>10mg/kg)',
      id: 'Buah kering, cuka fermentasi, dan pengawet (>10mg/kg)',
    },
  },
];

export const ALLERGEN_DISCLAIMER: Record<string, string> = {
  tr: '⚠️ Alerjen Bilgisi: Menüdeki alerjen bilgileri işletme beyanına dayanmaktadır. Mutfak ve servis ortamlarında çapraz bulaşma (cross-contamination) riski bulunabileceğinden, ciddi gıda alerjisi veya intoleransı olan misafirlerimizin sipariş öncesinde servis personeline bilgi vermesi önemle rica olunur.',
  en: '⚠️ Allergen Notice: Allergen information is based on declarations provided by the venue. Due to potential cross-contamination during preparation and service, guests with severe food allergies or intolerances are kindly requested to inform our staff before ordering.',
  de: '⚠️ Allergenhinweis: Die Allergenangaben basieren auf Angaben des Betriebs. Wegen möglicher Kreuzkontamination bitten wir Gäste mit schweren Allergien, vor der Bestellung das Servicepersonal zu informieren.',
  es: '⚠️ Aviso de Alérgenos: La información sobre alérgenos se basa en las declaraciones del establecimiento. Debido al riesgo de contaminación cruzada, rogamos a los clientes con alergias graves que informen al personal antes de realizar su pedido.',
  fr: '⚠️ Information Allergènes: Les informations sur les allergènes reposent sur les déclarations de l’établissement. En raison du risque de contamination croisée, les personnes allergiques sont priées d’en informer le personnel avant de commander.',
  ja: '⚠️ アレルギー情報：本メニューのアレルギー情報は店舗からの申告に基づいています。調理および提供過程において微量の混入（コンタミネーション）の可能性があるため、重度のアレルギーをお持ちのお客様は、ご注文前に必ずスタッフへお知らせください。',
  zh: '⚠️ 过敏原提示：菜单上的过敏原信息均根据餐厅申报提供。由于在烹饪与备餐过程中可能存在交叉污染的风险，患有严重食物过敏或不耐受的顾客，请在点餐前务必向服务人员说明。',
  ru: '⚠️ Информация об аллергенах: Сведения об аллергенах основаны на декларации заведения. Из-за риска перекрестного контакта при приготовлении блюд, гостям с серьезной пищевой аллергией или непереносимостью настоятельно рекомендуется сообщить об этом персоналу перед заказом.',
  ar: '⚠️ تنبيه الحساسية: تستند معلومات مسببات الحساسية في القائمة إلى إقرارات المنشأة. نظراً لاحتمال حدوث تلوث متبادل أثناء التحضير والخدمة، يُرجى من الضيوف الذين يعانون من حساسية شديدة إبلاغ فريق الخدمة قبل تقديم الطلب.',
  pt: '⚠️ Aviso de Alérgenos: As informações sobre alérgenos baseiam-se nas declarações do estabelecimento. Devido ao risco de contaminação cruzada durante a preparação e serviço, solicitamos aos clientes com alergias graves que informem a equipa antes de efetuar o pedido.',
  id: '⚠️ Informasi Alergen: Informasi alergen dalam menu ini didasarkan pada deklarasi pihak restoran. Mengingat potensi kontaminasi silang selama proses pengolahan dan penyajian, tamu dengan alergi parah atau intoleransi makanan dimohon untuk memberitahukan staf kami sebelum memesan.',
};

export function getAllergenLabel(id: string, lang: string = 'tr'): string {
  const item = ALLERGEN_CATALOG.find((a) => a.id === id);
  if (!item) return id;
  return item.names[lang] || item.names.en || item.names.tr || id;
}

export function getAllergenIcon(id: string): string {
  const item = ALLERGEN_CATALOG.find((a) => a.id === id);
  return item ? item.icon : '⚠️';
}

export function getAllergenDetail(id: string, lang: string = 'tr'): string {
  const item = ALLERGEN_CATALOG.find((a) => a.id === id);
  if (!item) return '';
  return item.details[lang] || item.details.en || item.details.tr || '';
}
